import sqlite3

conn = sqlite3.connect("studentmanage.db")

cur = conn.cursor()

# cur.execute('''
# CREATE TABLE TBLOGIN(LOGINID INTEGER PRIMARY KEY AUTOINCREMENT,
# USERNAME TEXT NOT NULL,
# PASSWORD TEXT NOT NULL,
# ROLE TEXT NOT NULL);''')

# cur.execute('''
# CREATE TABLE TBSTUDENT(
# STUDENTID INTEGER PRIMARY KEY AUTOINCREMENT,
# FULLNAME TEXT NOT NULL,
# EMAIL TEXT NOT NULL,
# AGE INTEGER NOT NULL,
# PHONE TEXT NOT NULL,
# GENDER TEXT NOT NULL,
# DEPARTMENT TEXT NOT NULL,
# LOGINID INTEGER, FOREIGN KEY (LOGINID) REFERENCES TBLOGIN(LOGINID));''')

# cur.execute('''
# CREATE TABLE TBTEACHER(
# TEACHERID INTEGER PRIMARY KEY AUTOINCREMENT,
# FULLNAME TEXT NOT NULL,
# EMAIL TEXT NOT NULL,
# PHONE TEXT NOT NULL,
# GENDER TEXT NOT NULL,
# DEPARTMENT TEXT NOT NULL,
# LOGINID INTEGER, FOREIGN KEY (LOGINID) REFERENCES TBLOGIN(LOGINID));''')

# cur.execute('''
# CREATE TABLE TBADMIN(
# ADMINID INTEGER PRIMARY KEY AUTOINCREMENT,
# FULLNAME TEXT NOT NULL,
# EMAIL TEXT NOT NULL,
# LOGINID INTEGER, FOREIGN KEY (LOGINID) REFERENCES TBLOGIN(LOGINID));''')

# cur.execute("INSERT INTO TBLOGIN(USERNAME, PASSWORD, ROLE) VALUES ('asvvinbiju', 'Aswin*6242&', 'admin');")

# cur.execute("SELECT LOGINID FROM TBLOGIN WHERE ROLE='admin';")

# id = cur.fetchone()[0]

# cur.execute("INSERT INTO TBADMIN(FULLNAME, EMAIL, LOGINID) VALUES ('Aswin Biju', 'aswinnbijuu@gmail.com', ?)", (id,))

# cur.execute("UPDATE TBLOGIN SET USERNAME='aswinbiju' WHERE LOGINID=1;")

# cur.execute("DELETE FROM TBADMIN;")
# cur.execute("DELETE FROM TBSTUDENT;")
# cur.execute("DELETE FROM TBLOGIN;")
# cur.execute("DELETE FROM TBTEACHER;")

# cur.execute("ALTER TABLE TBTEACHER ADD COLUMN APPROVE TEXT;")

# cur.execute("UPDATE TBTEACHER SET APPROVE='NOT APPROVED';")

# cur.execute("UPDATE TBTEACHER SET APPROVE='APPROVED' WHERE LOGINID=2;")

conn.commit()
conn.close()